// Mocks generated by Mockito 5.3.2 from annotations
// in weather/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i12;
import 'dart:typed_data' as _i13;

import 'package:async/async.dart' as _i3;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:weather/data/datasources/local_data_source.dart' as _i10;
import 'package:weather/data/datasources/remote_data_source.dart' as _i8;
import 'package:weather/data/models/weather_model.dart' as _i9;
import 'package:weather/domain/entities/city.dart' as _i2;
import 'package:weather/domain/entities/weather.dart' as _i7;
import 'package:weather/domain/repositories/weather_repository.dart' as _i4;
import 'package:weather/domain/usecases/get_weather_use_case.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCity_0 extends _i1.SmartFake implements _i2.City {
  _FakeCity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_1<T> extends _i1.SmartFake implements _i3.Result<T> {
  _FakeResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherRepository_2 extends _i1.SmartFake
    implements _i4.WeatherRepository {
  _FakeWeatherRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_4 extends _i1.SmartFake
    implements _i5.StreamedResponse {
  _FakeStreamedResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepository extends _i1.Mock implements _i4.WeatherRepository {
  @override
  _i6.Stream<_i4.ResultWithState<_i7.Weather>> getCurrentWeather(
          _i2.City? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [city],
        ),
        returnValue: _i6.Stream<_i4.ResultWithState<_i7.Weather>>.empty(),
        returnValueForMissingStub:
            _i6.Stream<_i4.ResultWithState<_i7.Weather>>.empty(),
      ) as _i6.Stream<_i4.ResultWithState<_i7.Weather>>);
  @override
  _i6.Future<_i2.City> getLastSelectedCity() => (super.noSuchMethod(
        Invocation.method(
          #getLastSelectedCity,
          [],
        ),
        returnValue: _i6.Future<_i2.City>.value(_FakeCity_0(
          this,
          Invocation.method(
            #getLastSelectedCity,
            [],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.City>.value(_FakeCity_0(
          this,
          Invocation.method(
            #getLastSelectedCity,
            [],
          ),
        )),
      ) as _i6.Future<_i2.City>);
  @override
  _i6.Future<dynamic> setLastSelectedCity(_i2.City? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastSelectedCity,
          [city],
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i8.RemoteDataSource {
  @override
  _i6.Future<_i3.Result<_i9.WeatherModel>> getCurrentWeather(_i2.City? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [city],
        ),
        returnValue: _i6.Future<_i3.Result<_i9.WeatherModel>>.value(
            _FakeResult_1<_i9.WeatherModel>(
          this,
          Invocation.method(
            #getCurrentWeather,
            [city],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Result<_i9.WeatherModel>>.value(
                _FakeResult_1<_i9.WeatherModel>(
          this,
          Invocation.method(
            #getCurrentWeather,
            [city],
          ),
        )),
      ) as _i6.Future<_i3.Result<_i9.WeatherModel>>);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i10.LocalDataSource {
  @override
  _i6.Future<_i3.Result<_i9.WeatherModel>> getSavedWeather(_i2.City? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedWeather,
          [city],
        ),
        returnValue: _i6.Future<_i3.Result<_i9.WeatherModel>>.value(
            _FakeResult_1<_i9.WeatherModel>(
          this,
          Invocation.method(
            #getSavedWeather,
            [city],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Result<_i9.WeatherModel>>.value(
                _FakeResult_1<_i9.WeatherModel>(
          this,
          Invocation.method(
            #getSavedWeather,
            [city],
          ),
        )),
      ) as _i6.Future<_i3.Result<_i9.WeatherModel>>);
  @override
  _i6.Future<dynamic> saveWeather(
    _i2.City? city,
    _i9.WeatherModel? weather,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWeather,
          [
            city,
            weather,
          ],
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
  @override
  _i6.Future<dynamic> setLastSelectedCity(_i2.City? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastSelectedCity,
          [city],
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
  @override
  _i6.Future<_i2.City> getLastSelectedCity() => (super.noSuchMethod(
        Invocation.method(
          #getLastSelectedCity,
          [],
        ),
        returnValue: _i6.Future<_i2.City>.value(_FakeCity_0(
          this,
          Invocation.method(
            #getLastSelectedCity,
            [],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.City>.value(_FakeCity_0(
          this,
          Invocation.method(
            #getLastSelectedCity,
            [],
          ),
        )),
      ) as _i6.Future<_i2.City>);
}

/// A class which mocks [LoadWeatherUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadWeatherUseCase extends _i1.Mock
    implements _i11.LoadWeatherUseCase {
  @override
  _i4.WeatherRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWeatherRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeWeatherRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.WeatherRepository);
  @override
  _i6.Stream<_i4.ResultWithState<_i7.Weather>> execute(_i2.City? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [city],
        ),
        returnValue: _i6.Stream<_i4.ResultWithState<_i7.Weather>>.empty(),
        returnValueForMissingStub:
            _i6.Stream<_i4.ResultWithState<_i7.Weather>>.empty(),
      ) as _i6.Stream<_i4.ResultWithState<_i7.Weather>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  @override
  _i6.Future<_i5.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i5.Response>);
  @override
  _i6.Future<_i5.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i5.Response>);
  @override
  _i6.Future<_i5.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);
  @override
  _i6.Future<_i5.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);
  @override
  _i6.Future<_i5.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);
  @override
  _i6.Future<_i5.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);
  @override
  _i6.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<String>.value(''),
        returnValueForMissingStub: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
  @override
  _i6.Future<_i13.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
        returnValueForMissingStub:
            _i6.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
      ) as _i6.Future<_i13.Uint8List>);
  @override
  _i6.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i6.Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_4(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_4(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i6.Future<_i5.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
